#host = 'localhost'
#user = 'user1'
#password = 'demo'
#database = 'news'
#data_form = 'subdistrict_info'
#sql = "insert into {} ( subdistrict, positive, positive_time, issue_time, deblocked) values('{}','1','{}','3','4')"

db:
    host: localhost
    user: root
    password: '123456'
    database: demo
    port: 3306